1.List Processing

In [31]:
num=list(range(1,11))
print(num)
odd=[]
for num in range (1,11):
 if num%2==0:
  continue
 else:
  odd.append(num)
print("list of odd:",odd)
final=[]
for num in odd:
  final.append(num*5)
print("final list:",final)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list of odd: [1, 3, 5, 7, 9]
final list: [5, 15, 25, 35, 45]


2.Shallow vs Deep Copy

In [41]:
import copy
list1=[[1,2],[3,4]]
shallow=copy.copy(list1)
deep=copy.deepcopy(list1)
print("shallow copy:",shallow)
print("deep copy:",deep)
shallow[0][0]=100
deep[0][0]=999
print("new shallow copy:",shallow)
print("new deep copy:",deep)

shallow copy: [[1, 2], [3, 4]]
deep copy: [[1, 2], [3, 4]]
new shallow copy: [[100, 2], [3, 4]]
new deep copy: [[999, 2], [3, 4]]


3.Dictionary with Nested Data

In [48]:

student={
    "name":"Alice",
    "grade":{
        "math":85,
        "science" : 92

    },
    "passed":"true"

    }
student["grade"]["math"]=95
student["grade"]["english"]=88
avg=(student["grade"]["math"]+student["grade"]["english"]+student["grade"]["science"])/3
print("Average Grade:",avg)
del student["passed"]
print(student)

Average Grade: 91.66666666666667
{'name': 'Alice', 'grade': {'math': 95, 'science': 92, 'english': 88}}


4.NumPy Array Operations

In [47]:
import numpy as np
array=np.arange(1,13)
shape=array.reshape(3,4)
multiarray=shape*2
print(multiarray)
second_col=multiarray[:,1]
print("second column:",second_col)
row=multiarray.sum(axis=1)
print("Row sum:",row)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
second column: [ 4 12 20]
Row sum: [20 52 84]
