In [5]:
import numpy as np


In [6]:
a=np.array([1,8,9])
print(a)

[1 8 9]


In [7]:
b=np.array([[1,2,3],[2,6,7]])
print(b)

[[1 2 3]
 [2 6 7]]


Get Dimension

In [8]:
b.ndim

2

Get Shape

In [9]:
b.shape

(2, 3)

Reshape

In [10]:
b.reshape(3,2)

array([[1, 2],
       [3, 2],
       [6, 7]])

Get type

In [11]:
a.dtype

dtype('int64')

Size

In [18]:
a.itemsize
b.itemsize

8